version: '3'

services:

#### Mysql ####
  mysql:
    image: mysql:5.7
    volumes:
        - ./data/mysql:/var/lib/mysql
        #- mysql_data:/var/lib/mysql
    expose:
      - 3306
#    ports:
#      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=app
    restart: on-failure

#### Redis ####
  redis:
    image: redis:3.2.11
    expose: 
      - "6379"
#    ports:
#      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis:/data
    restart: on-failure

#### phpmyadmin ####
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    links:
        - mysql:db
    depends_on:
      - mysql
    restart: on-failure

#### Go ####
  go:
    build:
      context: ./go
    depends_on:
      - mysql
      - redis
    restart: on-failure
    ports:
      - "${GO_PORT}:1323"

